# Generated by Django 5.0.6 on 2024-05-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_education_ordinal_remove_experience_ordinal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='logo',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='experience',
            name='logo',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
