# Generated by Django 5.0.6 on 2024-05-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_education_a_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(to='portfolio.skill'),
        ),
    ]
