# Generated by Django 5.0.6 on 2024-05-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='web app', max_length=100),
            preserve_default=False,
        ),
    ]
