# Generated by Django 5.0.6 on 2024-05-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_customuser_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='repoID',
            field=models.CharField(default='idrepo', max_length=100),
            preserve_default=False,
        ),
    ]
