# Generated by Django 5.0.6 on 2025-01-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_project_repo_project_repoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cv',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
