# Generated by Django 5.0.6 on 2025-01-18 23:13

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_customuser_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cv',
            field=models.FileField(blank=True, upload_to='uploads/', validators=[portfolio.models.validate_pdf]),
        ),
    ]
