# Generated by Django 5.0.6 on 2024-05-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_customuser_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='programming_language',
            field=models.ManyToManyField(related_name='projects', to='portfolio.programming'),
        ),
    ]
