# Generated by Django 5.0.6 on 2024-05-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_programming_project_programming_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='programming',
            name='logo',
            field=models.ImageField(default='uploads/Python_logo.svg', upload_to='uploads/'),
        ),
    ]
