# Generated by Django 5.0.6 on 2024-05-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_programming_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='ordinal',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='ordinal',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ordinal',
        ),
    ]
