# Generated by Django 5.0.6 on 2024-05-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_education_logo_experience_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='a_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='a_level_subjects_and_grades',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_level',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
