# Generated by Django 5.0.6 on 2024-05-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_customuser_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.CharField(default='Jan 2023 - Mar 2023', max_length=100),
            preserve_default=False,
        ),
    ]
