# Generated by Django 5.0.6 on 2024-05-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_customuser_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='github',
            field=models.URLField(),
        ),
    ]
